# Generated by Django 3.1.2 on 2020-10-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msteams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msteams',
            name='prof',
            field=models.CharField(default='Prof', max_length=100),
        ),
        migrations.AlterField(
            model_name='msteams',
            name='subject',
            field=models.CharField(max_length=10),
        ),
    ]
