# Generated by Django 3.1.2 on 2020-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msteams', '0002_auto_20201021_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='msteams',
            name='days',
            field=models.CharField(default='MON', max_length=27),
        ),
        migrations.AddField(
            model_name='msteams',
            name='time',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
